import {
  help,
  commands,
  about,
  lineup,
  voyage,
  gate,
  event,
  link,
  ping,
  weather,
  matrix,
  history,
  historyAdmin,
} from "./static";
import {
  bootSequence,
  wakeSequence,
  welcomeMessage,
  resumeMessage,
} from "./boot";
import {
  status,
  dateTime,
  swearWord,
  whoami,
  whoisStann,
  whoisMarcus,
  whoisNusnoom,
  whoisUnknown,
  sudoStann,
  sudoError,
  echoError,
  echoOutput,
  commandNotFound,
  settingsApply,
  nameSet,
  nameCurrent,
  nameCleared,
  nameEmpty,
  nameInvalid,
  systems,
} from "./user";
import {
  liveHeader,
  liveOffline,
  liveNoName,
  liveExit,
  liveTooFast,
  liveError,
} from "./live";
import {
  adminDenied,
  adminHelp,
  adminUnlocked,
  adminLiveOpened,
  adminLiveScheduled,
  adminLiveClosed,
  adminLiveNotFound,
  adminLiveDeleted,
  adminLiveCleared,
  adminSessionStatus,
  adminError,
  adminLoginSuccess,
  adminLoginFail,
  adminLogoutSuccess,
  adminAnnSent,
  adminAnnCleared,
  announcementBanner,
} from "./admin";
import { transmit } from "./transmit";

export const COMMAND_TEXTS = {
  help,
  commands,
  about,
  lineup,
  voyage,
  gate,
  event,
  link,
  ping,
  weather,
  matrix,
  history,
  historyAdmin,
  bootSequence,
  wakeSequence,
  welcomeMessage,
  resumeMessage,
  status,
  dateTime,
  swearWord,
  whoami,
  whoisStann,
  whoisMarcus,
  whoisNusnoom,
  whoisUnknown,
  sudoStann,
  sudoError,
  echoError,
  echoOutput,
  commandNotFound,
  settingsApply,
  nameSet,
  nameCurrent,
  nameCleared,
  nameEmpty,
  nameInvalid,
  systems,
  liveHeader,
  liveOffline,
  liveNoName,
  liveExit,
  liveTooFast,
  liveError,
  adminDenied,
  adminHelp,
  adminUnlocked,
  adminLiveOpened,
  adminLiveScheduled,
  adminLiveClosed,
  adminLiveNotFound,
  adminLiveDeleted,
  adminLiveCleared,
  adminSessionStatus,
  adminError,
  adminLoginSuccess,
  adminLoginFail,
  adminLogoutSuccess,
  adminAnnSent,
  adminAnnCleared,
  announcementBanner,
  transmit,
};
